name: Build on request
on: [workflow_dispatch]

jobs:
  Linux:
    name: Build linux version
    runs-on: ubuntu-20.04
    timeout-minutes: 120

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Ubuntu - install opengl lua5.1 luajit
      run: sudo apt update && sudo apt install -y libglew-dev liblua5.1-0-dev libluajit-5.1-dev

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v7
      with:
        vcpkgArguments: >
          boost-iostreams boost-asio boost-system boost-variant boost-lockfree boost-beast glew 
          boost-filesystem boost-uuid libogg libvorbis zlib opengl libzip openal-soft bzip2
          boost-process openssl physfs
        vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
        vcpkgTriplet: x64-linux
        vcpkgGitCommitId: 761c81d43335a5d5ccc2ec8ad90bd7e2cbba734e

    - name: Build with CMake
      uses: lukka/run-cmake@v3
      with:
        buildDirectory: ${{ runner.workspace }}/build
        cmakeAppendedArgs: '-G Ninja -DCMAKE_BUILD_TYPE="Release" -DVERSION=${{github.run_number}}'
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        useVcpkgToolchainFile: true

    - name: Change name
      run: |
        mv '${{ runner.workspace }}/build/otclient' '${{ runner.workspace }}/build/otclient_linux'

    - name: Upload otclient
      uses: actions/upload-artifact@v4
      with:
        name: Download-binaries
        path: |
          ${{ runner.workspace }}/build/otclient_linux
        if-no-files-found: error
